# Generated by Django 4.2.3 on 2023-09-11 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0004_alter_student_blood_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="batch",
        ),
        migrations.RemoveField(
            model_name="student",
            name="classs",
        ),
    ]
