# Generated by Django 4.2.3 on 2023-08-24 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_schedule_date_alter_classs_numeric_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="description",
        ),
    ]
