# Generated by Django 4.2.3 on 2023-09-18 16:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0004_remove_batch_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"ordering": ["date", "time"]},
        ),
    ]
