# Generated by Django 4.2.3 on 2023-09-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0005_alter_schedule_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="code",
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
