# Generated by Django 6.0.6 on 2026-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_tenant_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="is_required",
            field=models.BooleanField(default=True),
        ),
    ]
