version: "3.8"

services:
  redis:
    image: redis:7.0.10-alpine
    container_name: coaching_redis
    ports:
      - "6379:6379"
    networks:
      - coaching_management

  db:
    image: postgres:15-alpine
    container_name: coaching_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=coaching_management
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - coaching_management

  api:
    container_name: coaching_api
    build: ./backend
    env_file:
      - ./backend/.env
    command: >
      bash -c "python manage.py migrate &&
               python manage.py load_users &&
               python manage.py seed &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    # develop:
    #   watch:
    #     - path: ./backend
    #       target: /app
    #       action: sync
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - coaching_management

  # celery:
  #   container_name: coaching_celery
  #   build: ./backend
  #   env_file:
  #     - ./backend/.env
  #   command: celery -A backend worker -l INFO
  #   volumes:
  #     - ./backend:/app
  #   depends_on:
  #     - redis
  #     - db
  #     - api
  #   networks:
  #     - coaching_management

  web:
    container_name: coaching_web
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/app
    # develop:
    #   watch:
    #     - path: ./frontend/package.json
    #       action: rebuild
    #     - path: ./frontend/package-lock.json
    #       action: rebuild
    #     - path: ./frontend/yarn.lock
    #       action: rebuild
    #     - path: ./frontend
    #       target: /app
    #       action: sync

    networks:
      - coaching_management

networks:
  coaching_management:
