# Generated by Django 4.2.3 on 2023-07-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_user_created_at_alter_user_phone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ["-id"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("A", "Admin"),
                    ("AS", "Admin Staff"),
                    ("OA", "Organization Admin"),
                    ("OS", "Organization Staff"),
                    ("S", "student"),
                    ("T", "teacher"),
                ],
                max_length=2,
                null=True,
            ),
        ),
    ]
