# Generated by Django 4.2.3 on 2023-08-23 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_alter_user_phone_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("admin_staff", "Admin Staff"),
                    ("org_admin", "Organization Admin"),
                    ("org_staff", "Organization Staff"),
                    ("student", "student"),
                    ("teacher", "teacher"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
