# Generated by Django 6.0.6 on 2026-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0009_normalize_superuser_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("admin_staff", "Admin Staff"),
                    ("org_admin", "Organization Admin"),
                    ("org_staff", "Organization Staff"),
                    ("student", "student"),
                    ("teacher", "teacher"),
                    ("guardian", "guardian"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
