# Generated by Django 6.0.6 on 2026-08-02 09:22

import django.core.validators
import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0010_exam_is_required"),
        ("student", "0013_studentguardian"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_eligible", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enrollment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_candidates",
                        to="student.enroll",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="candidates",
                        to="organization.examtype",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exam_candidates",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": ["student__student_id"],
            },
        ),
        migrations.CreateModel(
            name="ExamMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("exempt", "Exempt"),
                        ],
                        default="present",
                        max_length=8,
                    ),
                ),
                (
                    "obtained_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "workflow_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("verified", "Verified"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks",
                        to="assessment.examcandidate",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_exam_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="marks",
                        to="organization.exam",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_exam_marks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["candidate__student__student_id"],
            },
        ),
        migrations.CreateModel(
            name="GradeScale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="GradeBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "minimum_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "maximum_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("grade", models.CharField(max_length=10)),
                ("grade_point", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="assessment.gradescale",
                    ),
                ),
            ],
            options={
                "ordering": ["-minimum_percentage"],
            },
        ),
        migrations.CreateModel(
            name="Outcome",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "total_obtained",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "total_possible",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade", models.CharField(max_length=10)),
                ("grade_point", models.DecimalField(decimal_places=2, max_digits=4)),
                ("has_passed", models.BooleanField()),
                ("rank", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outcomes",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "student__student_id"],
            },
        ),
        migrations.CreateModel(
            name="OutcomeLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("exempt", "Exempt"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "obtained_mark",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("total_mark", models.DecimalField(decimal_places=2, max_digits=8)),
                ("pass_mark", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("grade", models.CharField(blank=True, max_length=10)),
                (
                    "grade_point",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("has_passed", models.BooleanField()),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="organization.exam",
                    ),
                ),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="assessment.outcome",
                    ),
                ),
            ],
            options={
                "ordering": ["exam__date", "exam__subject__name"],
            },
        ),
        migrations.CreateModel(
            name="ResultDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("portal", "Portal")], max_length=8
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=8,
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("failure_message", models.TextField(blank=True)),
                (
                    "outcome",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="assessment.outcome",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result_deliveries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResultPublication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("published", "Published"),
                            ("superseded", "Superseded"),
                        ],
                        default="published",
                        max_length=10,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("show_rank", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="result_publications",
                        to="organization.examtype",
                    ),
                ),
                (
                    "grade_scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="assessment.gradescale",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="published_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddField(
            model_name="outcome",
            name="publication",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="outcomes",
                to="assessment.resultpublication",
            ),
        ),
        migrations.AddConstraint(
            model_name="examcandidate",
            constraint=models.UniqueConstraint(
                fields=("organization", "exam_type", "student"),
                name="unique_candidate_per_exam_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="exammark",
            constraint=models.UniqueConstraint(
                fields=("organization", "exam", "candidate"),
                name="unique_mark_per_exam_candidate",
            ),
        ),
        migrations.AddConstraint(
            model_name="exammark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("obtained_mark__isnull", True),
                    ("obtained_mark__gte", 0),
                    _connector="OR",
                ),
                name="exam_mark_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="exammark",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("attendance_status", "present"),
                    ("obtained_mark__isnull", True),
                    _connector="OR",
                ),
                name="non_present_mark_is_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradescale",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="unique_grade_scale_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("minimum_percentage__lte", models.F("maximum_percentage"))
                ),
                name="grade_band_percentage_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="gradeband",
            constraint=models.UniqueConstraint(
                fields=("scale", "grade"), name="unique_grade_per_scale"
            ),
        ),
        migrations.AddConstraint(
            model_name="outcomeline",
            constraint=models.UniqueConstraint(
                fields=("outcome", "exam"), name="unique_outcome_line_per_exam"
            ),
        ),
        migrations.AddConstraint(
            model_name="resultdelivery",
            constraint=models.UniqueConstraint(
                fields=("outcome", "recipient", "channel"),
                name="unique_result_delivery",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultpublication",
            constraint=models.UniqueConstraint(
                fields=("organization", "exam_type", "version"),
                name="unique_publication_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="resultpublication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "published")),
                fields=("organization", "exam_type"),
                name="one_current_publication_per_exam_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="outcome",
            constraint=models.UniqueConstraint(
                fields=("publication", "student"),
                name="unique_outcome_per_publication_student",
            ),
        ),
    ]
