# Generated by Django 6.0.6 on 2026-08-02 05:38

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import organization.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organization", "0009_tenant_constraints"),
        ("student", "0011_tenant_and_ledger_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("invoice_number", models.CharField(max_length=40)),
                (
                    "issue_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enroll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice",
                        to="student.enroll",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-issue_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=80)),
                ("sequence", models.PositiveSmallIntegerField()),
                ("due_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installments",
                        to="finance.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="OverdueReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("email", "Email"), ("manual", "Manual")],
                        default="email",
                        max_length=8,
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reminders",
                        to="finance.invoice",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=80)),
                (
                    "method_type",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank", "Bank transfer"),
                            ("mobile", "Mobile banking"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("instructions", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expense_number", models.CharField(max_length=40)),
                (
                    "expense_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("vendor", models.CharField(blank=True, max_length=120)),
                ("description", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("posted", "Posted"), ("void", "Void")],
                        default="posted",
                        max_length=8,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.expensecategory",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expenses",
                        to="finance.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CashReconciliation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "opening_balance",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "counted_balance",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("closed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "closed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cash_reconciliations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reconciliations",
                        to="finance.paymentmethod",
                    ),
                ),
            ],
            options={
                "ordering": ["-business_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed amount"),
                            ("percentage", "Percentage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("valid_from", models.DateField(blank=True, null=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScholarshipAward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "awarded_on",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enroll",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarship_award",
                        to="student.enroll",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_set",
                        to="organization.organization",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="finance.scholarship",
                    ),
                ),
            ],
            options={
                "ordering": ["-awarded_on", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="expensecategory",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="unique_expense_category_per_org_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("organization", "invoice_number"),
                name="unique_invoice_number_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.CheckConstraint(
                condition=models.Q(("issue_date__lte", models.F("due_date"))),
                name="invoice_due_not_before_issue",
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.UniqueConstraint(
                fields=("invoice", "sequence"),
                name="unique_invoice_installment_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gt", 0)),
                name="installment_sequence_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="installment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)),
                name="installment_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentmethod",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="unique_payment_method_per_org_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.UniqueConstraint(
                fields=("organization", "expense_number"),
                name="unique_expense_number_per_org",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="cashreconciliation",
            constraint=models.UniqueConstraint(
                fields=("organization", "payment_method", "business_date"),
                name="unique_daily_payment_method_reconciliation",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("opening_balance__gte", 0)),
                name="reconciliation_opening_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cashreconciliation",
            constraint=models.CheckConstraint(
                condition=models.Q(("counted_balance__gte", 0)),
                name="reconciliation_counted_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("organization"),
                name="unique_scholarship_per_org_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gt", 0)), name="scholarship_value_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "fixed"),
                    ("value__lte", Decimal("100.00")),
                    _connector="OR",
                ),
                name="scholarship_percentage_not_above_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("valid_from__isnull", True),
                    ("valid_until__isnull", True),
                    ("valid_from__lte", models.F("valid_until")),
                    _connector="OR",
                ),
                name="scholarship_dates_ordered",
            ),
        ),
        migrations.AddConstraint(
            model_name="scholarshipaward",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="scholarship_award_positive"
            ),
        ),
    ]
