# Generated by Django 6.0.6 on 2026-08-02 05:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_backfill_finance_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashreconciliation",
            name="collections",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashreconciliation",
            name="expected_balance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashreconciliation",
            name="expenses",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="cashreconciliation",
            name="variance",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
    ]
