# Generated by Django 4.2.3 on 2023-07-20 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_alter_student_address_alter_student_contact_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="contact_no",
        ),
    ]
