# Generated by Django 4.2.3 on 2023-07-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_remove_student_contact_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
