# Generated by Django 4.2.3 on 2023-09-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0005_remove_student_batch_remove_student_classs"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                db_index=True, default="asdf", max_length=50, unique=True
            ),
            preserve_default=False,
        ),
    ]
