# Generated by Django 6.0.6 on 2026-08-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("student", "0011_tenant_and_ledger_constraints"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="installment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.installment",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transactions",
                to="finance.paymentmethod",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reference_number",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
