# Generated by Django 6.0.6 on 2026-08-02 09:22

import django.db.models.deletion
import organization.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_exam_is_required"),
        ("student", "0012_transaction_installment_transaction_payment_method_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentGuardian",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("other", "Other"),
                        ],
                        default="guardian",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("result_email_enabled", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "guardian",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        default=organization.models.get_legacy_organization_pk,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_guardians",
                        to="organization.organization",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guardian_links",
                        to="student.student",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "-is_primary",
                    "guardian__first_name",
                    "guardian__last_name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "student", "guardian"),
                        name="unique_guardian_link_per_student",
                    )
                ],
            },
        ),
    ]
